        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 18 16:29:41 2010
        MODULE GEMINI__genmod
          INTERFACE 
            SUBROUTINE GEMINI(KLON,KLAT,KLEV)!,KSVAR,KACDG,KACDG2)
              USE DECOMP
              INTEGER(KIND=4), INTENT(IN) :: KLEV
              INTEGER(KIND=4), INTENT(IN) :: KLAT
              INTEGER(KIND=4), INTENT(IN) :: KLON
            END SUBROUTINE GEMINI
          END INTERFACE 
        END MODULE GEMINI__genmod
