        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 18 16:32:59 2010
        MODULE GETECOPATH__genmod
          INTERFACE 
            SUBROUTINE GETECOPATH(ECOPATH,RESOLUTION)
              CHARACTER(LEN=128) :: ECOPATH
              INTEGER(KIND=4) :: RESOLUTION
            END SUBROUTINE GETECOPATH
          END INTERFACE 
        END MODULE GETECOPATH__genmod
