        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 18 16:32:59 2010
        MODULE GETGTOPO30PATH__genmod
          INTERFACE 
            SUBROUTINE GETGTOPO30PATH(GTOPO30_PATH)
              CHARACTER(LEN=128) :: GTOPO30_PATH
            END SUBROUTINE GETGTOPO30PATH
          END INTERFACE 
        END MODULE GETGTOPO30PATH__genmod
